# Generated by Django 4.1.1 on 2022-09-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='apellido',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='profesion',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
