# Generated by Django 4.1.1 on 2022-09-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0002_rename_apellido_producto_ubicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajero',
            old_name='añosExperiencia',
            new_name='anosExperiencia',
        ),
    ]
