# Generated by Django 4.1.1 on 2022-09-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0003_rename_añosexperiencia_cajero_anosexperiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='camada',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
    ]
