# Generated by Django 4.1.1 on 2022-09-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0004_cliente_camada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajero',
            name='camada',
            field=models.IntegerField(default=54),
            preserve_default=False,
        ),
    ]
