# Generated by Django 4.1.1 on 2022-09-24 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0005_cajero_camada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajero',
            old_name='camada',
            new_name='ca',
        ),
    ]
