# Generated by Django 4.1.1 on 2022-09-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0006_rename_camada_cajero_ca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cajero',
            old_name='ca',
            new_name='camada',
        ),
    ]
