# Generated by Django 4.1.1 on 2022-09-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0007_rename_ca_cajero_camada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cajero',
            name='anosExperiencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
    ]
