# Generated by Django 4.1.1 on 2022-09-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuper', '0008_remove_cajero_anosexperiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='camada',
            field=models.IntegerField(default=454),
            preserve_default=False,
        ),
    ]
